### ISSUE TITLE
False positives

### ISSUE THREAD

**Issue by joshp23** [SweBarre/log-login#8]
Haven't been able to track it down, but there are numerous false positives in the login log, none having a username identified with them. It appears as if log-login is logging some other event.

**Comment by SweBarre** [comment]
Hi, I'm not able to reproduce this.
Any suggestion on how I setup a reproduction of this problem?

Cheers

**Comment by joshp23** [comment]
Not sure. 

I've got a standard YOURLS pulled from the master branch on a pretty standard Ubuntu 14.04 with latest updates.

Other plugins installed:
- Anti spam	1.0.4
- Compliance	1.0
- Don't Log Crawlers	1.2
- Don't Track Admins	1.2	
- Hide Referrer	1.0	
- Inline QRCodes
- Phishtank-2.0	
- Public Prefix-N-Shorten	1.0	
- Separate Users	0.3

Using the "Sleeky" front page with[ OZH's http:bl php](http://planetozh.com/blog/my-projects/honey-pot-httpbl-simple-php-script/) added to the header.

I suppose the only way forward would be to test these one by one. I can try to rule them out by turning off these elements one by one and seeing if the behavior stops. Since I just turned on Separate Users, I think that can be ruled out...

**Comment by joshp23** [comment]
I just wrote a plugin that logs http:bl hits. It too is giving double entries.

Not sure what that could be. But perhaps it's the particular public index. Using.
